/**
 * Asset Ingestion Pipeline
 * Handles file validation, format detection, and asset processing.
 * Maps to PRD sections 2.5 and FR-02.
 */

import { v4 as uuid } from 'uuid';
import type { AssetReference, AssetFormat, ValidationMessage } from '@/types';

/** Supported import formats with metadata */
export const SUPPORTED_FORMATS: Record<
  AssetFormat,
  { extensions: string[]; mimeTypes: string[]; description: string; maxSizeMB: number }
> = {
  glb: {
    extensions: ['.glb'],
    mimeTypes: ['model/gltf-binary'],
    description: 'GL Binary (recommended for 3D models)',
    maxSizeMB: 50,
  },
  gltf: {
    extensions: ['.gltf'],
    mimeTypes: ['model/gltf+json'],
    description: 'GL Transmission Format',
    maxSizeMB: 50,
  },
  obj: {
    extensions: ['.obj'],
    mimeTypes: ['text/plain'],
    description: 'Wavefront OBJ (basic geometry)',
    maxSizeMB: 30,
  },
  fbx: {
    extensions: ['.fbx'],
    mimeTypes: ['application/octet-stream'],
    description: 'Autodesk FBX',
    maxSizeMB: 50,
  },
  png: {
    extensions: ['.png'],
    mimeTypes: ['image/png'],
    description: 'PNG image (textures, labels)',
    maxSizeMB: 10,
  },
  jpg: {
    extensions: ['.jpg', '.jpeg'],
    mimeTypes: ['image/jpeg'],
    description: 'JPEG image (textures, backgrounds)',
    maxSizeMB: 10,
  },
  hdr: {
    extensions: ['.hdr'],
    mimeTypes: ['image/vnd.radiance'],
    description: 'HDR environment map',
    maxSizeMB: 30,
  },
};

/** Get all accepted file extensions as a flat list */
export function getAcceptedExtensions(): string[] {
  return Object.values(SUPPORTED_FORMATS).flatMap((f) => f.extensions);
}

/** Get a human-readable list of accepted formats */
export function getAcceptedFormatsDescription(): string {
  return Object.entries(SUPPORTED_FORMATS)
    .map(([key, value]) => `${key.toUpperCase()} (${value.description})`)
    .join(', ');
}

/** Detect asset format from file name */
export function detectFormat(fileName: string): AssetFormat | null {
  const ext = '.' + fileName.split('.').pop()?.toLowerCase();
  for (const [format, info] of Object.entries(SUPPORTED_FORMATS)) {
    if (info.extensions.includes(ext)) {
      return format as AssetFormat;
    }
  }
  return null;
}

/** Validate a file before ingestion */
export function validateFile(file: File): ValidationMessage[] {
  const messages: ValidationMessage[] = [];
  const format = detectFormat(file.name);

  if (!format) {
    messages.push({
      id: uuid(),
      ruleId: 'QC-01',
      severity: 'blocker',
      message: `Unsupported file format: "${file.name}". Accepted formats: ${getAcceptedExtensions().join(', ')}`,
      fix: 'Convert your file to GLB format for best compatibility.',
    });
    return messages;
  }

  const formatInfo = SUPPORTED_FORMATS[format];
  const sizeMB = file.size / (1024 * 1024);

  if (sizeMB > formatInfo.maxSizeMB) {
    messages.push({
      id: uuid(),
      ruleId: 'QC-07',
      severity: 'blocker',
      message: `File is ${sizeMB.toFixed(1)}MB, which exceeds the ${formatInfo.maxSizeMB}MB limit for ${format.toUpperCase()} files.`,
      fix: 'Reduce the file size by optimizing geometry, compressing textures, or using a lower resolution.',
    });
  }

  if (sizeMB > formatInfo.maxSizeMB * 0.7) {
    messages.push({
      id: uuid(),
      ruleId: 'QC-07',
      severity: 'warning',
      message: `File is ${sizeMB.toFixed(1)}MB (${Math.round((sizeMB / formatInfo.maxSizeMB) * 100)}% of limit). Large assets may affect performance.`,
      fix: 'Consider optimizing the asset for faster loading.',
    });
  }

  return messages;
}

/** Create an asset reference from a validated file */
export function createAssetFromFile(file: File): AssetReference {
  const format = detectFormat(file.name)!;
  const validationErrors = validateFile(file);
  const hasBlocker = validationErrors.some((m) => m.severity === 'blocker');

  return {
    id: uuid(),
    name: file.name.replace(/\.[^.]+$/, ''),
    format,
    url: URL.createObjectURL(file),
    fileSizeBytes: file.size,
    status: hasBlocker ? 'error' : 'processing',
    metadata: {
      originalFileName: file.name,
      mimeType: file.type,
    },
    validationErrors,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}

/** Simulate asset processing (thumbnail generation, optimization) */
export async function processAsset(asset: AssetReference): Promise<AssetReference> {
  // In production, this would call a real processing pipeline
  await new Promise((resolve) => setTimeout(resolve, 500));

  return {
    ...asset,
    status: 'ready',
    thumbnailUrl: undefined, // Would be generated by processing
    updatedAt: new Date().toISOString(),
  };
}
